### ISSUE TITLE
New dropbox authorisation key

### ISSUE THREAD

**Issue by Npnha** [alekseynemiro/nemiro.oauth.dll#25]
Hello dear alekseynemiro.
I've not yet started using your library and I have question for you.
Is your library supports new Dropbox authorisation method? (After mail & pass input, Dropbox show u a key, that should be used in application). Example of key attached as screenshot.
![3](https://cloud.githubusercontent.com/assets/22908208/25741775/04582bdc-3195-11e7-958d-539b36ffd121.jpg)

Thank you!

**Comment by alekseynemiro** [comment]
What version of the library are you using?

I checked with **Nemiro.OAuth.LoginForms v1.6**, it works correctly.

Versions below **v1.4** have this problem, because **Dropbox** changed the entry form code.

If you are using version **Nemiro.OAuth.LoginForms v1.6** and watch this problem, please tell which operating system you are using and what version of **Internet Explorer** you have.

**Comment by Npnha** [comment]
Hi alekseynemiro.
I had problem in my code and now can confirm that everything works as expected.
Thank you for superfast answer!
